// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: simul_v1.4

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
void ui_event_SplashScreen(lv_event_t * e);
lv_obj_t * ui_SplashScreen;
lv_obj_t * ui_SplashContainer2;
lv_obj_t * ui_Image20;
lv_obj_t * ui_Image21;
lv_obj_t * ui_heart1;
lv_obj_t * ui_line1;
lv_obj_t * ui_Image22;
lv_obj_t * ui_cpr1;
lv_obj_t * ui_autor1;
// CUSTOM VARIABLES


// SCREEN: ui_MenuPricipal
void ui_MenuPricipal_screen_init(void);
lv_obj_t * ui_MenuPricipal;
lv_obj_t * ui_MenuContainer2;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label21;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Header4;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image7;
// CUSTOM VARIABLES


// SCREEN: ui_Training
void ui_Training_screen_init(void);
void ui_event_Training(lv_event_t * e);
lv_obj_t * ui_Training;
lv_obj_t * ui_TrainingContainer1;
lv_obj_t * ui_pDepth2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_depth;
lv_obj_t * ui_Label3;
lv_obj_t * ui_pFrec2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_frec;
lv_obj_t * ui_Label5;
lv_obj_t * ui_pGauge2;
lv_obj_t * ui_gauge2;
lv_obj_t * ui_pointer;
lv_obj_t * ui_Header3;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
void ui_event_btnInitTraining(lv_event_t * e);
lv_obj_t * ui_btnInitTraining;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Image6;
void ui_event_btnStopTraining(lv_event_t * e);
lv_obj_t * ui_btnStopTraining;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Stats2;
lv_obj_t * ui_statsBg2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label27;
lv_obj_t * ui_deep;
lv_obj_t * ui_correct;
lv_obj_t * ui_shallow;
void ui_event_btnBackTraining(lv_event_t * e);
lv_obj_t * ui_btnBackTraining;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Image12;
void ui_event_btnMetro(lv_event_t * e);
lv_obj_t * ui_btnMetro;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Image14;
// CUSTOM VARIABLES


// SCREEN: ui_Evaluation1
void ui_Evaluation1_screen_init(void);
void ui_event_Evaluation1(lv_event_t * e);
lv_obj_t * ui_Evaluation1;
lv_obj_t * ui_evaluation1Container;
lv_obj_t * ui_pData1;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label19;
lv_obj_t * ui_confTime;
lv_obj_t * ui_confCpm;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Header2;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image10;
void ui_event_btnInitEvaluation(lv_event_t * e);
lv_obj_t * ui_btnInitEvaluation;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Image23;
void ui_event_btnBackEvaluation(lv_event_t * e);
lv_obj_t * ui_btnBackEvaluation;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Image25;
void ui_event_btnConf2(lv_event_t * e);
lv_obj_t * ui_btnConf2;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Image26;
lv_obj_t * ui_pData2;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label16;
lv_obj_t * ui_evalTime;
lv_obj_t * ui_Label23;
void ui_event_btnStopEvaluation(lv_event_t * e);
lv_obj_t * ui_btnStopEvaluation;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Image16;
// CUSTOM VARIABLES


// SCREEN: ui_configuration
void ui_configuration_screen_init(void);
void ui_event_configuration(lv_event_t * e);
lv_obj_t * ui_configuration;
lv_obj_t * ui_ConfigContainer1;
lv_obj_t * ui_Header9;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Image17;
lv_obj_t * ui_pSelection;
lv_obj_t * ui_minDropdown;
lv_obj_t * ui_cpmDropdown;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label13;
void ui_event_btnBack5(lv_event_t * e);
lv_obj_t * ui_btnBack5;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Image27;
// CUSTOM VARIABLES


// SCREEN: ui_ResultsScreen
void ui_ResultsScreen_screen_init(void);
void ui_event_ResultsScreen(lv_event_t * e);
lv_obj_t * ui_ResultsScreen;
lv_obj_t * ui_EvaluationContainer2;
lv_obj_t * ui_pData4;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label42;
lv_obj_t * ui_confTime1;
lv_obj_t * ui_confCpm1;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Label47;
lv_obj_t * ui_Header1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image3;
void ui_event_btnBack1(lv_event_t * e);
lv_obj_t * ui_btnBack1;
lv_obj_t * ui_Label48;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Stats3;
lv_obj_t * ui_statsBg3;
lv_obj_t * ui_Label49;
lv_obj_t * ui_Label50;
lv_obj_t * ui_Label51;
lv_obj_t * ui_deep1;
lv_obj_t * ui_shallow1;
lv_obj_t * ui_correct1;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Label53;
lv_obj_t * ui_evalTime1;
lv_obj_t * ui_Label54;
lv_obj_t * ui_evalCpm;
lv_obj_t * ui_Label55;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_title[4] = {&ui_img_title1_png, &ui_img_title2_png, &ui_img_title3_png, &ui_img_title4_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SplashScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_MenuPricipal, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 6000, &ui_MenuPricipal_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Training, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Training_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Evaluation1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Evaluation1_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_configuration, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_configuration_screen_init);
    }
}

void ui_event_Training(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        load_training(e);
    }
}

void ui_event_btnInitTraining(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        init_training(e);
    }
}

void ui_event_btnStopTraining(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        stop_training(e);
    }
}

void ui_event_btnBackTraining(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuPricipal, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuPricipal_screen_init);
        btn_back_training(e);
    }
}

void ui_event_btnMetro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_btnMetro, LV_OBJ_FLAG_CHECKABLE, _UI_MODIFY_FLAG_ADD);
        toggle_metronome_event_handler(e);
    }
}

void ui_event_Evaluation1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        load_evaluation(e);
    }
}

void ui_event_btnInitEvaluation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        init_evaluation(e);
    }
}

void ui_event_btnBackEvaluation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuPricipal, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuPricipal_screen_init);
        btn_back_evaluation(e);
    }
}

void ui_event_btnConf2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_configuration, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_configuration_screen_init);
    }
}

void ui_event_btnStopEvaluation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        stop_evaluation(e);
    }
}

void ui_event_configuration(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        load_configuration(e);
    }
}

void ui_event_btnBack5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuPricipal, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuPricipal_screen_init);
        save_configuration(e);
    }
}

void ui_event_ResultsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        load_results(e);
    }
}

void ui_event_btnBack1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Evaluation1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Evaluation1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScreen_screen_init();
    ui_MenuPricipal_screen_init();
    ui_Training_screen_init();
    ui_Evaluation1_screen_init();
    ui_configuration_screen_init();
    ui_ResultsScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScreen);
}
