// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: simul_v1.4

#ifndef _SIMUL_V1_4_UI_H
#define _SIMUL_V1_4_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
void ui_event_SplashScreen(lv_event_t * e);
extern lv_obj_t * ui_SplashScreen;
extern lv_obj_t * ui_SplashContainer2;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_heart1;
extern lv_obj_t * ui_line1;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_cpr1;
extern lv_obj_t * ui_autor1;
// CUSTOM VARIABLES

// SCREEN: ui_MenuPricipal
void ui_MenuPricipal_screen_init(void);
extern lv_obj_t * ui_MenuPricipal;
extern lv_obj_t * ui_MenuContainer2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label21;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Header4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image7;
// CUSTOM VARIABLES

// SCREEN: ui_Training
void ui_Training_screen_init(void);
void ui_event_Training(lv_event_t * e);
extern lv_obj_t * ui_Training;
extern lv_obj_t * ui_TrainingContainer1;
extern lv_obj_t * ui_pDepth2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_depth;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_pFrec2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_frec;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_pGauge2;
extern lv_obj_t * ui_gauge2;
extern lv_obj_t * ui_pointer;
extern lv_obj_t * ui_Header3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
void ui_event_btnInitTraining(lv_event_t * e);
extern lv_obj_t * ui_btnInitTraining;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image6;
void ui_event_btnStopTraining(lv_event_t * e);
extern lv_obj_t * ui_btnStopTraining;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Stats2;
extern lv_obj_t * ui_statsBg2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_deep;
extern lv_obj_t * ui_correct;
extern lv_obj_t * ui_shallow;
void ui_event_btnBackTraining(lv_event_t * e);
extern lv_obj_t * ui_btnBackTraining;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image12;
void ui_event_btnMetro(lv_event_t * e);
extern lv_obj_t * ui_btnMetro;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image14;
// CUSTOM VARIABLES

// SCREEN: ui_Evaluation1
void ui_Evaluation1_screen_init(void);
void ui_event_Evaluation1(lv_event_t * e);
extern lv_obj_t * ui_Evaluation1;
extern lv_obj_t * ui_evaluation1Container;
extern lv_obj_t * ui_pData1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_confTime;
extern lv_obj_t * ui_confCpm;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Header2;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
void ui_event_btnInitEvaluation(lv_event_t * e);
extern lv_obj_t * ui_btnInitEvaluation;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Image23;
void ui_event_btnBackEvaluation(lv_event_t * e);
extern lv_obj_t * ui_btnBackEvaluation;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Image25;
void ui_event_btnConf2(lv_event_t * e);
extern lv_obj_t * ui_btnConf2;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_pData2;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_evalTime;
extern lv_obj_t * ui_Label23;
void ui_event_btnStopEvaluation(lv_event_t * e);
extern lv_obj_t * ui_btnStopEvaluation;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Image16;
// CUSTOM VARIABLES

// SCREEN: ui_configuration
void ui_configuration_screen_init(void);
void ui_event_configuration(lv_event_t * e);
extern lv_obj_t * ui_configuration;
extern lv_obj_t * ui_ConfigContainer1;
extern lv_obj_t * ui_Header9;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_pSelection;
extern lv_obj_t * ui_minDropdown;
extern lv_obj_t * ui_cpmDropdown;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label13;
void ui_event_btnBack5(lv_event_t * e);
extern lv_obj_t * ui_btnBack5;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Image27;
// CUSTOM VARIABLES

// SCREEN: ui_ResultsScreen
void ui_ResultsScreen_screen_init(void);
void ui_event_ResultsScreen(lv_event_t * e);
extern lv_obj_t * ui_ResultsScreen;
extern lv_obj_t * ui_EvaluationContainer2;
extern lv_obj_t * ui_pData4;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_confTime1;
extern lv_obj_t * ui_confCpm1;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Header1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
void ui_event_btnBack1(lv_event_t * e);
extern lv_obj_t * ui_btnBack1;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Stats3;
extern lv_obj_t * ui_statsBg3;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_deep1;
extern lv_obj_t * ui_shallow1;
extern lv_obj_t * ui_correct1;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_evalTime1;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_evalCpm;
extern lv_obj_t * ui_Label55;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_uner_png);    // assets/uner.png
LV_IMG_DECLARE(ui_img_ese_png);    // assets/ese.png
LV_IMG_DECLARE(ui_img_754372804);    // assets/cpr1-tranps.png
LV_IMG_DECLARE(ui_img_linea_png);    // assets/linea.png
LV_IMG_DECLARE(ui_img_training_png);    // assets/training.png
LV_IMG_DECLARE(ui_img_cpr_png);    // assets/cpr.png
LV_IMG_DECLARE(ui_img_title3_png);    // assets/title3.png
LV_IMG_DECLARE(ui_img_bat_png);    // assets/bat.png
LV_IMG_DECLARE(ui_img_gauge_png);    // assets/gauge.png
LV_IMG_DECLARE(ui_img_pointer_png);    // assets/pointer.png
LV_IMG_DECLARE(ui_img_title1_png);    // assets/title1.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_stop_png);    // assets/stop.png
LV_IMG_DECLARE(ui_img_stats_bg_png);    // assets/stats_bg.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_sound_on_png);    // assets/sound_on.png
LV_IMG_DECLARE(ui_img_title2_png);    // assets/title2.png
LV_IMG_DECLARE(ui_img_icon_conf_png);    // assets/icon_conf.png
LV_IMG_DECLARE(ui_img_title4_png);    // assets/title4.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
