// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: simul_v1.4

#include "../ui.h"

void ui_Evaluation1_screen_init(void)
{
    ui_Evaluation1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Evaluation1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_evaluation1Container = lv_obj_create(ui_Evaluation1);
    lv_obj_remove_style_all(ui_evaluation1Container);
    lv_obj_set_width(ui_evaluation1Container, 320);
    lv_obj_set_height(ui_evaluation1Container, 240);
    lv_obj_set_align(ui_evaluation1Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_evaluation1Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pData1 = lv_obj_create(ui_evaluation1Container);
    lv_obj_set_width(ui_pData1, 286);
    lv_obj_set_height(ui_pData1, 67);
    lv_obj_set_x(ui_pData1, 1);
    lv_obj_set_y(ui_pData1, -49);
    lv_obj_set_align(ui_pData1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pData1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pData1, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pData1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pData1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_pData1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -100);
    lv_obj_set_y(ui_Label11, 8);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Tiempo:");

    ui_Label14 = lv_label_create(ui_pData1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 46);
    lv_obj_set_y(ui_Label14, 8);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Tasa:");

    ui_Label19 = lv_label_create(ui_pData1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 2);
    lv_obj_set_y(ui_Label19, -19);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Parametros");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confTime = lv_label_create(ui_pData1);
    lv_obj_set_width(ui_confTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confTime, -51);
    lv_obj_set_y(ui_confTime, 8);
    lv_obj_set_align(ui_confTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confTime, "1:00");
    lv_obj_set_style_text_color(ui_confTime, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confCpm = lv_label_create(ui_pData1);
    lv_obj_set_width(ui_confCpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confCpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confCpm, 80);
    lv_obj_set_y(ui_confCpm, 8);
    lv_obj_set_align(ui_confCpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confCpm, "100");
    lv_obj_set_style_text_color(ui_confCpm, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confCpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_pData1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 111);
    lv_obj_set_y(ui_Label20, 8);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "cpm");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_pData1);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -20);
    lv_obj_set_y(ui_Label29, 8);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "min");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header2 = lv_obj_create(ui_evaluation1Container);
    lv_obj_set_width(ui_Header2, 309);
    lv_obj_set_height(ui_Header2, 29);
    lv_obj_set_x(ui_Header2, 2);
    lv_obj_set_y(ui_Header2, -106);
    lv_obj_set_align(ui_Header2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Header2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Header2, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Header2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_Header2);
    lv_img_set_src(ui_Image9, &ui_img_title2_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Image9, -58);
    lv_obj_set_y(ui_Image9, 0);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Header2);
    lv_img_set_src(ui_Image10, &ui_img_bat_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 67
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_Image10, 120);
    lv_obj_set_y(ui_Image10, 0);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnInitEvaluation = lv_btn_create(ui_evaluation1Container);
    lv_obj_set_width(ui_btnInitEvaluation, 55);
    lv_obj_set_height(ui_btnInitEvaluation, 20);
    lv_obj_set_x(ui_btnInitEvaluation, 123);
    lv_obj_set_y(ui_btnInitEvaluation, 95);
    lv_obj_set_align(ui_btnInitEvaluation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnInitEvaluation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnInitEvaluation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnInitEvaluation, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnInitEvaluation, lv_color_hex(0x4AAE52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnInitEvaluation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_btnInitEvaluation);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 5);
    lv_obj_set_y(ui_Label22, -1);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Inicio");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_img_create(ui_btnInitEvaluation);
    lv_img_set_src(ui_Image23, &ui_img_play_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 7
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_Image23, -17);
    lv_obj_set_y(ui_Image23, -1);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnBackEvaluation = lv_btn_create(ui_evaluation1Container);
    lv_obj_set_width(ui_btnBackEvaluation, 55);
    lv_obj_set_height(ui_btnBackEvaluation, 20);
    lv_obj_set_x(ui_btnBackEvaluation, -2);
    lv_obj_set_y(ui_btnBackEvaluation, 95);
    lv_obj_set_align(ui_btnBackEvaluation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBackEvaluation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBackEvaluation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnBackEvaluation, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnBackEvaluation, lv_color_hex(0x4073D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackEvaluation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_btnBackEvaluation);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 6);
    lv_obj_set_y(ui_Label40, -1);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "Volver");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image25 = lv_img_create(ui_btnBackEvaluation);
    lv_img_set_src(ui_Image25, &ui_img_back_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 7
    lv_obj_set_x(ui_Image25, -18);
    lv_obj_set_y(ui_Image25, -1);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnConf2 = lv_btn_create(ui_evaluation1Container);
    lv_obj_set_width(ui_btnConf2, 81);
    lv_obj_set_height(ui_btnConf2, 20);
    lv_obj_set_x(ui_btnConf2, -97);
    lv_obj_set_y(ui_btnConf2, 95);
    lv_obj_set_align(ui_btnConf2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnConf2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnConf2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnConf2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnConf2, lv_color_hex(0x699FD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnConf2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_btnConf2);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 5);
    lv_obj_set_y(ui_Label41, -1);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Configurar");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image26 = lv_img_create(ui_btnConf2);
    lv_img_set_src(ui_Image26, &ui_img_icon_conf_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Image26, -32);
    lv_obj_set_y(ui_Image26, 0);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pData2 = lv_obj_create(ui_evaluation1Container);
    lv_obj_set_width(ui_pData2, 286);
    lv_obj_set_height(ui_pData2, 67);
    lv_obj_set_x(ui_pData2, 0);
    lv_obj_set_y(ui_pData2, 32);
    lv_obj_set_align(ui_pData2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pData2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pData2, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pData2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pData2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_pData2);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -57);
    lv_obj_set_y(ui_Label30, 7);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Tiempo Restante:");

    ui_Label16 = lv_label_create(ui_pData2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 2);
    lv_obj_set_y(ui_Label16, -19);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Tiempo Evaluado");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_evalTime = lv_label_create(ui_pData2);
    lv_obj_set_width(ui_evalTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_evalTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_evalTime, 34);
    lv_obj_set_y(ui_evalTime, 8);
    lv_obj_set_align(ui_evalTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_evalTime, "01:00");
    lv_obj_set_style_text_color(ui_evalTime, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_evalTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_pData2);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 72);
    lv_obj_set_y(ui_Label23, 8);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "min");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnStopEvaluation = lv_btn_create(ui_evaluation1Container);
    lv_obj_set_width(ui_btnStopEvaluation, 55);
    lv_obj_set_height(ui_btnStopEvaluation, 20);
    lv_obj_set_x(ui_btnStopEvaluation, 60);
    lv_obj_set_y(ui_btnStopEvaluation, 95);
    lv_obj_set_align(ui_btnStopEvaluation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnStopEvaluation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnStopEvaluation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnStopEvaluation, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnStopEvaluation, lv_color_hex(0xFF6644), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnStopEvaluation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_btnStopEvaluation);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 5);
    lv_obj_set_y(ui_Label17, -1);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Parar");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_img_create(ui_btnStopEvaluation);
    lv_img_set_src(ui_Image16, &ui_img_stop_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 7
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_Image16, -17);
    lv_obj_set_y(ui_Image16, -1);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btnInitEvaluation, ui_event_btnInitEvaluation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnBackEvaluation, ui_event_btnBackEvaluation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnConf2, ui_event_btnConf2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnStopEvaluation, ui_event_btnStopEvaluation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Evaluation1, ui_event_Evaluation1, LV_EVENT_ALL, NULL);

}
