// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: simul_v1.4

#include "../ui.h"

void ui_MenuPricipal_screen_init(void)
{
    ui_MenuPricipal = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuPricipal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuContainer2 = lv_obj_create(ui_MenuPricipal);
    lv_obj_remove_style_all(ui_MenuContainer2);
    lv_obj_set_width(ui_MenuContainer2, 320);
    lv_obj_set_height(ui_MenuContainer2, 240);
    lv_obj_set_x(ui_MenuContainer2, 2);
    lv_obj_set_y(ui_MenuContainer2, 0);
    lv_obj_set_align(ui_MenuContainer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MenuContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_MenuContainer2);
    lv_obj_set_width(ui_Button1, 193);
    lv_obj_set_height(ui_Button1, 28);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, -45);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x4073D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 1);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Modo Entrenamiento");

    ui_Button2 = lv_btn_create(ui_MenuContainer2);
    lv_obj_set_width(ui_Button2, 193);
    lv_obj_set_height(ui_Button2, 28);
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, -5);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x4073D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 1);
    lv_obj_set_y(ui_Label21, 0);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Modo Evaluacion");

    ui_Button3 = lv_btn_create(ui_MenuContainer2);
    lv_obj_set_width(ui_Button3, 193);
    lv_obj_set_height(ui_Button3, 28);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, 34);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x4073D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 1);
    lv_obj_set_y(ui_Label31, 0);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Configuracion");

    ui_Header4 = lv_obj_create(ui_MenuContainer2);
    lv_obj_set_width(ui_Header4, 309);
    lv_obj_set_height(ui_Header4, 29);
    lv_obj_set_x(ui_Header4, -1);
    lv_obj_set_y(ui_Header4, -105);
    lv_obj_set_align(ui_Header4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Header4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Header4, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Header4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Header4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Header4);
    lv_img_set_src(ui_Image1, &ui_img_title3_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Image1, -80);
    lv_obj_set_y(ui_Image1, 1);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Header4);
    lv_img_set_src(ui_Image7, &ui_img_bat_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 67
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_Image7, 120);
    lv_obj_set_y(ui_Image7, 0);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
