// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: simul_v1.4

#include "../ui.h"

void ui_ResultsScreen_screen_init(void)
{
    ui_ResultsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ResultsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EvaluationContainer2 = lv_obj_create(ui_ResultsScreen);
    lv_obj_remove_style_all(ui_EvaluationContainer2);
    lv_obj_set_width(ui_EvaluationContainer2, 320);
    lv_obj_set_height(ui_EvaluationContainer2, 240);
    lv_obj_set_align(ui_EvaluationContainer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EvaluationContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pData4 = lv_obj_create(ui_EvaluationContainer2);
    lv_obj_set_width(ui_pData4, 309);
    lv_obj_set_height(ui_pData4, 60);
    lv_obj_set_x(ui_pData4, 2);
    lv_obj_set_y(ui_pData4, -55);
    lv_obj_set_align(ui_pData4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pData4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pData4, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pData4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pData4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_pData4);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -109);
    lv_obj_set_y(ui_Label24, 9);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Tiempo:");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_pData4);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, 57);
    lv_obj_set_y(ui_Label42, 9);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "Tasa:");
    lv_obj_set_style_text_font(ui_Label42, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confTime1 = lv_label_create(ui_pData4);
    lv_obj_set_width(ui_confTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confTime1, -64);
    lv_obj_set_y(ui_confTime1, 9);
    lv_obj_set_align(ui_confTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confTime1, "2:00");
    lv_obj_set_style_text_color(ui_confTime1, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confCpm1 = lv_label_create(ui_pData4);
    lv_obj_set_width(ui_confCpm1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confCpm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confCpm1, 86);
    lv_obj_set_y(ui_confCpm1, 9);
    lv_obj_set_align(ui_confCpm1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confCpm1, "110");
    lv_obj_set_style_text_color(ui_confCpm1, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confCpm1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_pData4);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 115);
    lv_obj_set_y(ui_Label45, 9);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "cpm");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label45, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_pData4);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, -77);
    lv_obj_set_y(ui_Label46, -18);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "Parametros de evaluacion");
    lv_obj_set_style_text_font(ui_Label46, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_pData4);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, -30);
    lv_obj_set_y(ui_Label47, 9);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "min");
    lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label47, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header1 = lv_obj_create(ui_EvaluationContainer2);
    lv_obj_set_width(ui_Header1, 309);
    lv_obj_set_height(ui_Header1, 29);
    lv_obj_set_x(ui_Header1, 2);
    lv_obj_set_y(ui_Header1, -106);
    lv_obj_set_align(ui_Header1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Header1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Header1, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Header1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Header1);
    lv_img_set_src(ui_Image2, &ui_img_title2_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Image2, -58);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Header1);
    lv_img_set_src(ui_Image3, &ui_img_bat_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 67
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_Image3, 120);
    lv_obj_set_y(ui_Image3, 0);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnBack1 = lv_btn_create(ui_EvaluationContainer2);
    lv_obj_set_width(ui_btnBack1, 55);
    lv_obj_set_height(ui_btnBack1, 20);
    lv_obj_set_x(ui_btnBack1, 124);
    lv_obj_set_y(ui_btnBack1, 101);
    lv_obj_set_align(ui_btnBack1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBack1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnBack1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnBack1, lv_color_hex(0x4073D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBack1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_btnBack1);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, 6);
    lv_obj_set_y(ui_Label48, -1);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "Volver");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_btnBack1);
    lv_img_set_src(ui_Image11, &ui_img_back_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 7
    lv_obj_set_x(ui_Image11, -18);
    lv_obj_set_y(ui_Image11, -1);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Stats3 = lv_obj_create(ui_EvaluationContainer2);
    lv_obj_set_width(ui_Stats3, 309);
    lv_obj_set_height(ui_Stats3, 102);
    lv_obj_set_x(ui_Stats3, 2);
    lv_obj_set_y(ui_Stats3, 30);
    lv_obj_set_align(ui_Stats3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Stats3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Stats3, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stats3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statsBg3 = lv_img_create(ui_Stats3);
    lv_img_set_src(ui_statsBg3, &ui_img_stats_bg_png);
    lv_obj_set_width(ui_statsBg3, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_statsBg3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_statsBg3, 2);
    lv_obj_set_y(ui_statsBg3, 24);
    lv_obj_set_align(ui_statsBg3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_statsBg3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_statsBg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label49 = lv_label_create(ui_statsBg3);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -97);
    lv_obj_set_y(ui_Label49, -10);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "Correctas");
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0x313030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label49, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_statsBg3);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, 0);
    lv_obj_set_y(ui_Label50, -10);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "Superficiales");
    lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0x313030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label50, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_statsBg3);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 96);
    lv_obj_set_y(ui_Label51, -10);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "Profundas");
    lv_obj_set_style_text_color(ui_Label51, lv_color_hex(0x313030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label51, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deep1 = lv_label_create(ui_statsBg3);
    lv_obj_set_width(ui_deep1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deep1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deep1, 103);
    lv_obj_set_y(ui_deep1, 4);
    lv_obj_set_align(ui_deep1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deep1, "0 %");
    lv_obj_set_style_text_color(ui_deep1, lv_color_hex(0xAE130C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deep1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_deep1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shallow1 = lv_label_create(ui_statsBg3);
    lv_obj_set_width(ui_shallow1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shallow1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shallow1, 5);
    lv_obj_set_y(ui_shallow1, 4);
    lv_obj_set_align(ui_shallow1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shallow1, "0 %");
    lv_obj_set_style_text_color(ui_shallow1, lv_color_hex(0x8B8B50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shallow1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shallow1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_correct1 = lv_label_create(ui_statsBg3);
    lv_obj_set_width(ui_correct1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_correct1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_correct1, -91);
    lv_obj_set_y(ui_correct1, 4);
    lv_obj_set_align(ui_correct1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_correct1, "0 %");
    lv_obj_set_style_text_color(ui_correct1, lv_color_hex(0x09930A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_correct1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_correct1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Stats3);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, -114);
    lv_obj_set_y(ui_Label52, -39);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "Resultados");
    lv_obj_set_style_text_font(ui_Label52, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Stats3);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -108);
    lv_obj_set_y(ui_Label53, -15);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "Tiempo:");
    lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_evalTime1 = lv_label_create(ui_Stats3);
    lv_obj_set_width(ui_evalTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_evalTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_evalTime1, -61);
    lv_obj_set_y(ui_evalTime1, -15);
    lv_obj_set_align(ui_evalTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_evalTime1, "0:00");
    lv_obj_set_style_text_color(ui_evalTime1, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_evalTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Stats3);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, 17);
    lv_obj_set_y(ui_Label54, -15);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "Tasa Promedio:");
    lv_obj_set_style_text_font(ui_Label54, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_evalCpm = lv_label_create(ui_Stats3);
    lv_obj_set_width(ui_evalCpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_evalCpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_evalCpm, 81);
    lv_obj_set_y(ui_evalCpm, -15);
    lv_obj_set_align(ui_evalCpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_evalCpm, "0");
    lv_obj_set_style_text_color(ui_evalCpm, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_evalCpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_Stats3);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 113);
    lv_obj_set_y(ui_Label55, -15);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "cpm");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnBack1, ui_event_btnBack1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResultsScreen, ui_event_ResultsScreen, LV_EVENT_ALL, NULL);

}
