// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: simul_v1.4

#include "../ui.h"

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SplashContainer2 = lv_obj_create(ui_SplashScreen);
    lv_obj_remove_style_all(ui_SplashContainer2);
    lv_obj_set_width(ui_SplashContainer2, 320);
    lv_obj_set_height(ui_SplashContainer2, 240);
    lv_obj_set_align(ui_SplashContainer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SplashContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_SplashContainer2);
    lv_img_set_src(ui_Image20, &ui_img_uner_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 363
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 97
    lv_obj_set_x(ui_Image20, -101);
    lv_obj_set_y(ui_Image20, -101);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_img_create(ui_SplashContainer2);
    lv_img_set_src(ui_Image21, &ui_img_ese_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 520
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 119
    lv_obj_set_x(ui_Image21, 97);
    lv_obj_set_y(ui_Image21, -101);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_heart1 = lv_img_create(ui_SplashContainer2);
    lv_img_set_src(ui_heart1, &ui_img_754372804);
    lv_obj_set_width(ui_heart1, LV_SIZE_CONTENT);   /// 196
    lv_obj_set_height(ui_heart1, LV_SIZE_CONTENT);    /// 185
    lv_obj_set_x(ui_heart1, -5);
    lv_obj_set_y(ui_heart1, -1);
    lv_obj_set_align(ui_heart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heart1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heart1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_line1 = lv_img_create(ui_SplashContainer2);
    lv_img_set_src(ui_line1, &ui_img_linea_png);
    lv_obj_set_width(ui_line1, LV_SIZE_CONTENT);   /// 111
    lv_obj_set_height(ui_line1, LV_SIZE_CONTENT);    /// 6
    lv_obj_set_x(ui_line1, 66);
    lv_obj_set_y(ui_line1, 70);
    lv_obj_set_align(ui_line1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_line1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_line1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_SplashContainer2);
    lv_img_set_src(ui_Image22, &ui_img_training_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 86
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_Image22, 46);
    lv_obj_set_y(ui_Image22, 55);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cpr1 = lv_img_create(ui_SplashContainer2);
    lv_img_set_src(ui_cpr1, &ui_img_cpr_png);
    lv_obj_set_width(ui_cpr1, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_cpr1, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_cpr1, -35);
    lv_obj_set_y(ui_cpr1, 33);
    lv_obj_set_align(ui_cpr1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cpr1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cpr1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_autor1 = lv_label_create(ui_SplashContainer2);
    lv_obj_set_width(ui_autor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autor1, -4);
    lv_obj_set_y(ui_autor1, 108);
    lv_obj_set_align(ui_autor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autor1, "Ing. Gustavo Di Stefano");
    lv_obj_set_style_text_font(ui_autor1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SplashScreen, ui_event_SplashScreen, LV_EVENT_ALL, NULL);

}
