// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: simul_v1.4

#include "../ui.h"

void ui_Training_screen_init(void)
{
    ui_Training = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Training, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TrainingContainer1 = lv_obj_create(ui_Training);
    lv_obj_remove_style_all(ui_TrainingContainer1);
    lv_obj_set_width(ui_TrainingContainer1, 320);
    lv_obj_set_height(ui_TrainingContainer1, 240);
    lv_obj_set_align(ui_TrainingContainer1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TrainingContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pDepth2 = lv_obj_create(ui_TrainingContainer1);
    lv_obj_set_width(ui_pDepth2, 108);
    lv_obj_set_height(ui_pDepth2, 49);
    lv_obj_set_x(ui_pDepth2, 101);
    lv_obj_set_y(ui_pDepth2, -65);
    lv_obj_set_align(ui_pDepth2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pDepth2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pDepth2, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pDepth2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pDepth2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_pDepth2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -2);
    lv_obj_set_y(ui_Label2, -13);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Profundidad");
    lv_label_set_recolor(ui_Label2, "true");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_depth = lv_label_create(ui_pDepth2);
    lv_obj_set_width(ui_depth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_depth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_depth, -18);
    lv_obj_set_y(ui_depth, 8);
    lv_obj_set_align(ui_depth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_depth, "0.0");
    lv_obj_set_style_text_color(ui_depth, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_depth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_depth, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_pDepth2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 12);
    lv_obj_set_y(ui_Label3, 8);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "cm");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pFrec2 = lv_obj_create(ui_TrainingContainer1);
    lv_obj_set_width(ui_pFrec2, 108);
    lv_obj_set_height(ui_pFrec2, 49);
    lv_obj_set_x(ui_pFrec2, 102);
    lv_obj_set_y(ui_pFrec2, -13);
    lv_obj_set_align(ui_pFrec2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pFrec2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pFrec2, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pFrec2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pFrec2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_pFrec2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -2);
    lv_obj_set_y(ui_Label4, -13);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Frecuencia");
    lv_label_set_recolor(ui_Label4, "true");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_frec = lv_label_create(ui_pFrec2);
    lv_obj_set_width(ui_frec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_frec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_frec, -21);
    lv_obj_set_y(ui_frec, 8);
    lv_obj_set_align(ui_frec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_frec, "0");
    lv_obj_set_style_text_color(ui_frec, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_frec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_frec, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_pFrec2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 16);
    lv_obj_set_y(ui_Label5, 8);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "cpm");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x467AD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pGauge2 = lv_obj_create(ui_TrainingContainer1);
    lv_obj_set_width(ui_pGauge2, 194);
    lv_obj_set_height(ui_pGauge2, 98);
    lv_obj_set_x(ui_pGauge2, -55);
    lv_obj_set_y(ui_pGauge2, -39);
    lv_obj_set_align(ui_pGauge2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pGauge2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pGauge2, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pGauge2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pGauge2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gauge2 = lv_img_create(ui_pGauge2);
    lv_img_set_src(ui_gauge2, &ui_img_gauge_png);
    lv_obj_set_width(ui_gauge2, LV_SIZE_CONTENT);   /// 163
    lv_obj_set_height(ui_gauge2, LV_SIZE_CONTENT);    /// 94
    lv_obj_set_x(ui_gauge2, 1);
    lv_obj_set_y(ui_gauge2, 2);
    lv_obj_set_align(ui_gauge2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gauge2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_gauge2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pointer = lv_img_create(ui_pGauge2);
    lv_img_set_src(ui_pointer, &ui_img_pointer_png);
    lv_obj_set_width(ui_pointer, LV_SIZE_CONTENT);   /// 56
    lv_obj_set_height(ui_pointer, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_pointer, 12);
    lv_obj_set_y(ui_pointer, 9);
    lv_obj_set_align(ui_pointer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pointer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pointer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_pointer, 14, 54);
    lv_img_set_angle(ui_pointer, -1300);

    ui_Header3 = lv_obj_create(ui_TrainingContainer1);
    lv_obj_set_width(ui_Header3, 309);
    lv_obj_set_height(ui_Header3, 29);
    lv_obj_set_x(ui_Header3, 2);
    lv_obj_set_y(ui_Header3, -106);
    lv_obj_set_align(ui_Header3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Header3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Header3, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Header3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Header3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Header3);
    lv_img_set_src(ui_Image4, &ui_img_title1_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_Image4, -55);
    lv_obj_set_y(ui_Image4, 1);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Header3);
    lv_img_set_src(ui_Image5, &ui_img_bat_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 67
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_Image5, 120);
    lv_obj_set_y(ui_Image5, 0);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnInitTraining = lv_btn_create(ui_TrainingContainer1);
    lv_obj_set_width(ui_btnInitTraining, 55);
    lv_obj_set_height(ui_btnInitTraining, 20);
    lv_obj_set_x(ui_btnInitTraining, 123);
    lv_obj_set_y(ui_btnInitTraining, 95);
    lv_obj_set_align(ui_btnInitTraining, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnInitTraining, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnInitTraining, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnInitTraining, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnInitTraining, lv_color_hex(0x4AAE52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnInitTraining, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_btnInitTraining);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 5);
    lv_obj_set_y(ui_Label6, -1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Inicio");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_btnInitTraining);
    lv_img_set_src(ui_Image6, &ui_img_play_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 7
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_Image6, -17);
    lv_obj_set_y(ui_Image6, -1);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnStopTraining = lv_btn_create(ui_TrainingContainer1);
    lv_obj_set_width(ui_btnStopTraining, 55);
    lv_obj_set_height(ui_btnStopTraining, 20);
    lv_obj_set_x(ui_btnStopTraining, 60);
    lv_obj_set_y(ui_btnStopTraining, 95);
    lv_obj_set_align(ui_btnStopTraining, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnStopTraining, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnStopTraining, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnStopTraining, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnStopTraining, lv_color_hex(0xF64031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnStopTraining, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_btnStopTraining);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 6);
    lv_obj_set_y(ui_Label7, -1);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Parar");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_btnStopTraining);
    lv_img_set_src(ui_Image13, &ui_img_stop_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image13, -18);
    lv_obj_set_y(ui_Image13, -1);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Stats2 = lv_obj_create(ui_TrainingContainer1);
    lv_obj_set_width(ui_Stats2, 309);
    lv_obj_set_height(ui_Stats2, 48);
    lv_obj_set_x(ui_Stats2, 2);
    lv_obj_set_y(ui_Stats2, 42);
    lv_obj_set_align(ui_Stats2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Stats2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Stats2, lv_color_hex(0x00BAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stats2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stats2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statsBg2 = lv_img_create(ui_Stats2);
    lv_img_set_src(ui_statsBg2, &ui_img_stats_bg_png);
    lv_obj_set_width(ui_statsBg2, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_statsBg2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_statsBg2, 0);
    lv_obj_set_y(ui_statsBg2, -1);
    lv_obj_set_align(ui_statsBg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_statsBg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_statsBg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_statsBg2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -97);
    lv_obj_set_y(ui_Label9, -10);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Correctas");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x313030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_statsBg2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, -10);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Superficiales");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x313030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_statsBg2);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 96);
    lv_obj_set_y(ui_Label27, -10);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Profundas");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x313030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deep = lv_label_create(ui_statsBg2);
    lv_obj_set_width(ui_deep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deep, 101);
    lv_obj_set_y(ui_deep, 4);
    lv_obj_set_align(ui_deep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deep, "0 %");
    lv_obj_set_style_text_color(ui_deep, lv_color_hex(0xAE130C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_deep, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_correct = lv_label_create(ui_statsBg2);
    lv_obj_set_width(ui_correct, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_correct, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_correct, -95);
    lv_obj_set_y(ui_correct, 4);
    lv_obj_set_align(ui_correct, LV_ALIGN_CENTER);
    lv_label_set_text(ui_correct, "0 %");
    lv_obj_set_style_text_color(ui_correct, lv_color_hex(0x09930A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_correct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_correct, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shallow = lv_label_create(ui_statsBg2);
    lv_obj_set_width(ui_shallow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shallow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shallow, 3);
    lv_obj_set_y(ui_shallow, 4);
    lv_obj_set_align(ui_shallow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shallow, "0 %");
    lv_obj_set_style_text_color(ui_shallow, lv_color_hex(0x8B8B50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shallow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shallow, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackTraining = lv_btn_create(ui_TrainingContainer1);
    lv_obj_set_width(ui_btnBackTraining, 55);
    lv_obj_set_height(ui_btnBackTraining, 20);
    lv_obj_set_x(ui_btnBackTraining, -2);
    lv_obj_set_y(ui_btnBackTraining, 95);
    lv_obj_set_align(ui_btnBackTraining, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBackTraining, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBackTraining, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnBackTraining, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnBackTraining, lv_color_hex(0x4073D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackTraining, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_btnBackTraining);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 6);
    lv_obj_set_y(ui_Label12, -1);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Volver");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_btnBackTraining);
    lv_img_set_src(ui_Image12, &ui_img_back_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image12, -18);
    lv_obj_set_y(ui_Image12, -1);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnMetro = lv_btn_create(ui_TrainingContainer1);
    lv_obj_set_width(ui_btnMetro, 93);
    lv_obj_set_height(ui_btnMetro, 20);
    lv_obj_set_x(ui_btnMetro, -103);
    lv_obj_set_y(ui_btnMetro, 95);
    lv_obj_set_align(ui_btnMetro, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnMetro, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnMetro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnMetro, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnMetro, lv_color_hex(0x4073D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnMetro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnMetro, lv_color_hex(0x2ED676), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnMetro, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label15 = lv_label_create(ui_btnMetro);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 9);
    lv_obj_set_y(ui_Label15, -1);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Metronomo");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_btnMetro);
    lv_img_set_src(ui_Image14, &ui_img_sound_on_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image14, -34);
    lv_obj_set_y(ui_Image14, 0);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btnInitTraining, ui_event_btnInitTraining, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnStopTraining, ui_event_btnStopTraining, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnBackTraining, ui_event_btnBackTraining, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnMetro, ui_event_btnMetro, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Training, ui_event_Training, LV_EVENT_ALL, NULL);

}
